name: Rust

on:
  push:
    tags:
      - "*"

jobs:
  build-win:
    runs-on: windows-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        working-directory: ./filo-clipboard
        run: cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./filo-clipboard/target/release/filo-clipboard.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
